baseURL: 'https://luojiahai.com/'
title: 'luojiahai'
paginate: 5
theme: 'paper'

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

languages:
  en:
    languageName: 'English'
    weight: 1

  zh:
    languageName: 'ä¸­æ–‡'
    weight: 2

    menu:
      main:
        - identifier: 'about'
          name: 'å…³äº'
          url: 'about'
          weight: 10
        - identifier: cv
          name: 'ç®€å†'
          url: 'cv'
          weight: 20
        - identifier: 'posts'
          name: 'å¸–å­'
          url: 'posts'
          weight: 30
        - identifier: 'archives'
          name: 'å½’æ¡£'
          url: 'archives'
          weight: 40
        - identifier: 'notes'
          name: 'ç¬”è®°'
          url: 'notes'
          weight: 50
        - identifier: 'search'
          name: 'æœç´¢'
          url: 'search'
          weight: 60

    params:
      dateFormat: '2006å¹´1æœˆ2æ—¥'

      homeInfo:
        title: '`> whoami`'
        content: |
          ğŸ–¥ï¸ æˆ‘æ˜¯ä¸€åè½¯ä»¶å¼€å‘å·¥ç¨‹å¸ˆã€‚

          ğŸ”­ æˆ‘ç›®å‰åœ¨åŠªåŠ›å·¥ä½œè°‹ç”Ÿã€‚

          ğŸŒ± æˆ‘ç›®å‰åœ¨å­¦ä¹ æœºå™¨å¦‚ä½•æ€è€ƒã€‚

          ğŸ“« å¦‚ä½•è”ç³»æˆ‘: `luo[at]jiahai.co`

          [é˜…è¯»æ›´å¤š](/about)â€¦

params:
  env: 'production'
  title: 'luojiahai'
  author: 'luojiahai'
  dateFormat: '2006-01-02'
  defaultTheme: 'dark' # dark, light

  enableAnchoredHeadings: true
  enableScrollToTop: true
  enableThemeToggle: true
  hideMeta: false
  hideSummary: false
  showBreadCrumbs: true
  showCodeCopyButtons: true
  showFullLanguageName: true
  showPageNums: false
  showToc: true
  tocOpen: false
  useHugoToc: true

  label:
    text: 'luojiahai'
    icon: '/apple-touch-icon.png'
    iconHeight: 25

  homeInfo:
    title: '`> whoami`'
    content: |
      ğŸ–¥ï¸ I am a software development engineer.

      ğŸ”­ I am currently working hard for a living.

      ğŸŒ± I am currently learning how machine thinks.

      ğŸ“« How to reach me: `luo[at]jiahai.co`

      [Read more](/about)â€¦

  socialIcons:
    - name: 'x'
      url: 'https://x.com/luojiahai/'
    - name: 'instagram'
      url: 'https://instagram.com/luojiahai/'
    - name: 'linkedin'
      url: 'https://linkedin.com/in/luojiahai/'
    - name: 'github'
      url: 'https://github.com/luojiahai/'

  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10
    keys: ['title', 'permalink', 'summary', 'content']

menu:
  main:
    - identifier: 'about'
      name: 'About'
      url: 'about'
      weight: 10
    - identifier: 'resume'
      name: 'RÃ©sumÃ©'
      url: 'resume'
      weight: 20
    - identifier: 'posts'
      name: 'Posts'
      url: 'posts'
      weight: 30
    - identifier: 'archives'
      name: 'Archives'
      url: 'archives'
      weight: 40
    - identifier: 'notes'
      name: 'Notes'
      url: 'notes'
      weight: 50
    - identifier: 'search'
      name: 'Search'
      url: 'search'
      weight: 60

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

outputs:
  home:
    - HTML
    - JSON
