baseURL: 'https://luojiahai.com/'
title: 'luojiahai'
paginate: 5
theme: 'paper'

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

languages:
  en:
    languageName: 'English'
    weight: 1

  zh:
    languageName: '‰∏≠Êñá'
    weight: 2

    menu:
      main:
        - identifier: 'about'
          name: 'ÂÖ≥‰∫é'
          url: 'about'
          weight: 10
        - identifier: cv
          name: 'ÁÆÄÂéÜ'
          url: 'cv'
          weight: 20
        - identifier: 'posts'
          name: 'Â∏ñÂ≠ê'
          url: 'posts'
          weight: 30
        - identifier: 'archives'
          name: 'ÂΩíÊ°£'
          url: 'archives'
          weight: 40
        - identifier: 'search'
          name: 'ÊêúÁ¥¢'
          url: 'search'
          weight: 50

    params:
      dateFormat: '2006Âπ¥1Êúà2Êó•'

      homeInfo:
        title: '`> whoami`'
        content: |
          ü•¢ ÊàëÊòØ‰∏Ä‰∏™ÁæéÈ£üÁà±Â•ΩËÄÖ„ÄÇ

          üñ•Ô∏è ÊàëÊòØ‰∏Ä‰∏™ËΩØ‰ª∂ÂºÄÂèëÂ∑•Á®ãÂ∏à„ÄÇ

          üì´ Â¶Ç‰ΩïËÅîÁ≥ªÊàë: `luo[at]jiahai.co`

          [ÈòÖËØªÊõ¥Â§ö](/about)‚Ä¶

params:
  env: 'production'
  title: 'luojiahai'
  author: 'luojiahai'
  dateFormat: '2006-01-02'
  defaultTheme: 'dark' # dark, light

  enableAnchoredHeadings: true
  enableScrollToTop: true
  enableThemeToggle: true
  hideMeta: false
  hideSummary: false
  showBreadCrumbs: true
  showCodeCopyButtons: true
  showFullLanguageName: true
  showPageNums: false
  showToc: true
  tocOpen: false
  useHugoToc: true

  label:
    text: 'luojiahai'
    icon: '/apple-touch-icon.png'
    iconHeight: 25

  homeInfo:
    title: '`> whoami`'
    content: |
      ü•¢ I am a food enthusiast.

      üñ•Ô∏è I am a software development engineer.

      üì´ How to reach me: `luo[at]jiahai.co`

      [Read more](/about)‚Ä¶

  socialIcons:
    - name: 'x'
      url: 'https://x.com/luojiahai/'
    - name: 'instagram'
      url: 'https://instagram.com/luojiahai/'
    - name: 'linkedin'
      url: 'https://linkedin.com/in/luojiahai/'
    - name: 'github'
      url: 'https://github.com/luojiahai/'

  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10
    keys: ['title', 'permalink', 'summary', 'content']

menu:
  main:
    - identifier: 'about'
      name: 'About'
      url: 'about'
      weight: 10
    - identifier: 'cv'
      name: 'Curriculum Vitae'
      url: 'cv'
      weight: 20
    - identifier: 'posts'
      name: 'Posts'
      url: 'posts'
      weight: 30
    - identifier: 'archives'
      name: 'Archives'
      url: 'archives'
      weight: 40
    - identifier: 'search'
      name: 'Search'
      url: 'search'
      weight: 50

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

outputs:
  home:
    - HTML
    - JSON
