baseURL: "https://luojiahai.com/"
title: luojiahai
paginate: 5
theme: paper

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1

  zh:
    languageName: "ğŸ‡¨ğŸ‡³ ä¸­æ–‡"
    weight: 2

    menu:
      main:
        - identifier: about
          name: å…³äº
          url: about
          weight: 10
        - identifier: posts
          name: å¸–å­
          url: posts
          weight: 20
        - identifier: archives
          name: å½’æ¡£
          url: archives
          weight: 30
        - identifier: search
          name: æœç´¢
          url: search
          weight: 40
        - identifier: cv
          name: ç®€å†
          url: cv
          weight: 50

    params:
      dateFormat: "2006å¹´1æœˆ2æ—¥"

      homeInfoParams:
        Title: "`:~$ whoami`"
        Content: |
          æˆ‘æ˜¯ä¸€ä¸ªç¾é£Ÿçˆ±å¥½è€…ã€‚

          æˆ‘æ˜¯ä¸€ä¸ªè½¯ä»¶å¼€å‘å·¥ç¨‹å¸ˆã€‚

          å¦‚ä½•è”ç³»æˆ‘: `luo[at]jiahai.co`

          [â€¦é˜…è¯»æ›´å¤š](/about)

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: luojiahai
  # description: ""
  # keywords: [""]
  author: luojiahai
  # images: [""] 
  dateFormat: "2006-01-02"
  defaultTheme: dark # dark, light
  
  enableAnchoredHeadings: true
  enableScrollToTop: true
  enableThemeToggle: true
  hideMeta: false
  hideSummary: false
  showBreadCrumbs: true
  showCodeCopyButtons: true
  showFullLanguageName: true
  showPageNums: false
  showRssButtonInSectionTermList: false
  showToc: true
  tocOpen: false
  useHugoToc: true

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "luojiahai"
    icon: /apple-touch-icon.png
    iconHeight: 25

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: luojiahai
    # subtitle: ""
    imageUrl: "/apple-touch-icon.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: profile
    buttons:
      - name: CV
        url: cv

  # home-info mode
  homeInfoParams:
    Title: "`:~$ whoami`"
    Content: |
      I am a food enthusiast.

      I am a software development engineer.

      How to reach me: `luo[at]jiahai.co`

      [â€¦ Read more](/about)

  socialIcons:
    - name: x
      url: "https://x.com/luojiahai/"
    - name: instagram
      url: "https://instagram.com/luojiahai/"
    - name: linkedin
      url: "https://linkedin.com/in/luojiahai/"
    - name: github
      url: "https://github.com/luojiahai/"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  # cover:
  #   hidden: true # hide everywhere but not in structured data
  #   hiddenInList: true # hide on list pages and home
  #   hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: About
      url: about
      weight: 10
    - identifier: posts
      name: Posts
      url: posts
      weight: 20
    - identifier: archives
      name: Archives
      url: archives
      weight: 30
    - identifier: search
      name: Search
      url: search
      weight: 40
    - identifier: cv
      name: Curriculum Vitae
      url: cv
      weight: 50

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
