baseURL: 'https://luojiahai.com/'
title: 'luojiahai'
paginate: 5
theme: 'paper'

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

languages:
  en:
    languageName: 'English'
    weight: 1

  zh:
    languageName: 'ä¸­æ–‡'
    weight: 2

    params:
      homeInfo:
        title: '`> whoami`'
        content: |
          ğŸ–¥ï¸ æˆ‘æ˜¯ä¸€åè½¯ä»¶å¼€å‘å·¥ç¨‹å¸ˆã€‚

          ğŸ”­ æˆ‘ç›®å‰åœ¨åŠªåŠ›å·¥ä½œè°‹ç”Ÿã€‚

          ğŸŒ± æˆ‘ç›®å‰åœ¨å­¦ä¹ æœºå™¨å¦‚ä½•æ€è€ƒã€‚

          ğŸ“« å¦‚ä½•è”ç³»æˆ‘: `luo[at]jiahai.co`

          [é˜…è¯»æ›´å¤šâ€¦](/about)

params:
  env: 'production'
  title: 'luojiahai'
  author: 'luojiahai'
  defaultTheme: 'dark' # dark, light

  enableAnchoredHeadings: true
  enableScrollToTop: true
  enableThemeToggle: true
  showMeta: true
  showSummary: true
  showBreadCrumbs: true
  showCodeCopyButtons: true
  showFullLanguageName: true
  showPageNums: false
  showPin: true
  showToc: true
  tocOpen: false
  useHugoToc: true

  label:
    text: 'luojiahai'
    icon: '/apple-touch-icon.png'
    iconHeight: 25

  homeInfo:
    title: '`> whoami`'
    content: |
      ğŸ–¥ï¸ I am a software development engineer.

      ğŸ”­ I am currently working hard for a living.

      ğŸŒ± I am currently learning how machine thinks.

      ğŸ“« How to reach me: `luo[at]jiahai.co`

      [Read moreâ€¦](/about)

  socialIcons:
    - name: 'x'
      url: 'https://x.com/luojiahai/'
    - name: 'instagram'
      url: 'https://instagram.com/luojiahai/'
    - name: 'linkedin'
      url: 'https://linkedin.com/in/luojiahai/'
    - name: 'github'
      url: 'https://github.com/luojiahai/'

  mainSections:
    - 'posts'

  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10
    keys: ['title', 'permalink', 'summary', 'content']

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

outputs:
  home:
    - HTML
    - JSON
